# Site settings
author: Jonah Flateman
title: Data Science
header-img: img/home-bg.png
email: jonahflateman@gmail.com
copyright_name: Jonah Flateman
description: > # this means to ignore newlines until "baseurl:"
  Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JonahFlateman

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
